const titleToFeature = {
  "Do you need Registration & Authorization?": "Authorization",
  "Will you allow users to complete a profile?": "Profile",
  "Do you need Chats in your app?": "Chats",
  "Do you need Group Chats in your app?": "Group Chats",
  "Will you send Notifications to your users?": "Notifications",
  "Will your app have a Splash screen?": "Splash Screen",
  "Will you need an Info screen in your app?": "Info Screen",
  "Will your app accept payments?": "Payments",
  "Do you need an Admin Panel in your app?": "Admin Panel",
  "Will your app have the Events screen?": "Events",
  "Do you need a Home screen in your app?": "Home Screen",
  "Will there be a screen to manage the Matches?": "Matches",
  "Does your app need a Tutorial?": "Tutorial",
  "Will you let users manage the Settings?": "Settings",
  "Do you want to let users Invite friends?": "Invite Friends",
  "Do you need a Locations screen?": "Locations",
  "Do you need a Contacts screen in your app?": "Contacts",
  "Will you let users organize Channels in your app?": "Channels",
  "Will users manage tracks in “Favorites”?": "Favorites",
  "Will you allow users to manage their playlists?": "Playlists",
  "Will users have access to other users pages?": "User Pages",
  "Will there be a Music player screen?": "Music Player",
  "Do you need separate pages for Artists?": "Artists Page",
  "Do you need separate pages for Albums?": "Albums Page",
  "Will there be a Product details screen?": "Product Details",
  "Will you let users manage a Shopping cart?": "Shopping Cart",
  "What will there be on the Add post screen?": "Add Post",
  "Will you let users customize their photos?": "Photo Customization",
  "Will you let jobseekers complete a Profile?": "Jobseeker Profile",
  "Will there be a Job description screen?": "Job Description",
  "Will you let employers complete a profile?": "Employer Profile",
  "Do you need a Post a Job screen?": "Post a Job",
  "Will there be a screen with Posted jobs?": "Posted Jobs",
  "Will the app show a list of Applicants to a job?": "Applicants",
  "Do you need a Payment screen for a Passenger’s app?": "Passenger Payments",
  "Do you need a screen with Promotions?": "Promotions",
  "Will there be a Help section?": "Help Section",
  "Will there be a Home screen?": "Home Screen",
  "Will you track users’ GPS Location?": "Location Tracking",
  "Will there be a Posts Feed in your app?": "Posts Feed",
  "Will you let Users create their Posts?": "Create Posts",
  "Will Users be able to Tab Friends?": "Tag Friends",
  "Do you need an Articles Feed in your app?": "Articles Feed",
  "Do you need a User’s Profile Screen?": "User Profile",
  "Will you let Users edit their own posts?": "Edit Posts",
  "Will there be a Following feature in your app?": "Following",
  "Do you need an Progress Calculators in your app?": "Progress Calculators",
  "Will there be a List of Trainings in your app?": "Trainings",
  "Will you let users create and manage a Training Plan?": "Training Plan",
  "Will there be an Award Screen in your app?": "Award Screen",
  "Do you need a Notifications screen in your app?": "Notifications Screen",
  "Do you need a Messages screen in your app?": "Messages",
  "Will there be a screen with app details in your app?": "App Details",
  "Will there be a Pregnancy Tracking screen?": "Pregnancy Tracking",
  "Will your app have a Shopping screen?": "Shopping Screen",
  "Do you need an Order screen?": "Order Screen",
  "Will there be a Blog in your app?": "Blog",
  "Do you need a Doctors’ side?": "Doctors' Side",
  "Do you need an Admin Panel?": "Admin Panel",
  "Will you let users Add Friends automatically?": "Auto Add Friends",
  "Does your app need a Main Screen?": "Main Screen",
  "Will users be able to Broadcast?": "Broadcast",
  "Will you show users Broadcast Statistics?": "Broadcast Stats",
  "Will you allow Group Broadcasts?": "Group Broadcasts",
  "Will Users be able to watch Replays?": "Replays",
  "Will you show the list of Live Broadcasts?": "Live Broadcasts",
  "Will you allow Location-based Broadcasts?": "Location-based Broadcasts",
  "Will there be a Notification Screen?": "Notification Screen",
  "Do you need a Screen that shows Users?": "Users Screen",
  "Will you show brief User Details?": "User Details",
  "Will there be Search in you app?": "Search",
  "Do you need a User Profile Screen?": "User Profile",
  "Will you allow users to edit a Profile?": "Edit Profile",
  "Will users manage the Notification Settings?": "Notification Settings",
  "Will users manage the Broadcast Settings?": "Broadcast Settings",
};
export default titleToFeature